apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  labels:
  {{- include "hextris-prod.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - hextris-prod.local
    secretName: '{{ .Release.Name }}-tls-secret'
  rules:
  - host: hextris-prod.local
    http:
      paths:
      - backend:
          service:
            name: '{{ .Release.Name }}-service'
            port:
              number: 80
        path: /
        pathType: Prefix