apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-tls-secret
  labels:
  {{- include "hextris-prod.labels" . | nindent 4 }}
data:
  tls.crt: {{ required "tls.Crt is required" .Values.tls.Crt | quote }}
  tls.key: {{ required "tls.Key is required" .Values.tls.Key | quote }}
type: kubernetes.io/tls